# Modules for Scientific Computing and Analysis

---

## Classes

Object-oriented programming is one of the most effective approaches to writing software. In object-oriented programming you write classes that represent real-world things and situations, and you create objects based on these classes. When you write a class, you define the general behavior that a whole category of objects can have. When you create individual objects from the class, each object is automatically equipped with the general behavior; you can then give each object whatever unique traits you desire. You’ll be amazed how well real-world situations can be modeled with object-oriented programming. 

In [1]:
class Stock():
    """A simple class to model a stock"""
    
    def __init__(self, name, ticker, market_cap, time_series):
        self.name = name
        self.ticker = ticker
        self.market_cap = market_cap
        self.time_series = time_series
        
    def add_price(self,date,price):
        self.time_series[date] = price
        
    def change_market_cap(self,new_cap):
        self.market_cap = new_cap

In [2]:
apple_stock = Stock("Apple", "AAPL", 1000000000000, {"2020/8/1":400.51, "2020/8/2":403.45})

In [3]:
apple_stock.time_series

{'2020/8/1': 400.51, '2020/8/2': 403.45}

In [4]:
apple_stock.ticker

'AAPL'

In [5]:
apple_stock.add_price("2020/8/3",411.60)

In [6]:
apple_stock.time_series

{'2020/8/1': 400.51, '2020/8/2': 403.45, '2020/8/3': 411.6}

### Inheritance 

You don’t always have to start from scratch when writing a class. If the class you’re writing is a specialized version of another class you wrote, you can use inheritance. When one class inherits from another, it automatically takes on all the attributes and methods of the first class. The original class is called the parent class, and the new class is the child class. The child class inherits every attribute and method from its parent class but is also free to define new attributes and methods of its own.

In [8]:
class Stock_future(Stock):
    
    def __init__(self, name, ticker, market_cap, time_series, expiry):
        super().__init__(name, ticker, market_cap, time_series)
        self.expiry = expiry
        
    def change_expiry(new_expiry):
        self.expiry = new_expiry
    

In [9]:
apple_future = Stock_future("Apple", "AAPL", 1000000000000, {"2020/8/1":400.51, "2020/8/2":403.45},"2020/8/30")

In [10]:
apple_future.expiry

'2020/8/30'

In [11]:
apple_future.time_series

{'2020/8/1': 400.51, '2020/8/2': 403.45}

In [12]:
apple_future.add_price("2020/8/3",411.60)

In [13]:
apple_future.time_series

{'2020/8/1': 400.51, '2020/8/2': 403.45, '2020/8/3': 411.6}

## File IO

Interfacing with files so that you can import data into your code is going to be very important to use. As we will see there are a number of ways to do this as well as a number of modules that provide the functionality we will need. We will start with the most basic approach, the open() function. This allows us to import a file from a given path and populate various data structures with it's contents.

In [14]:
filepath = "/Users/michael/python_work/pi_digits.txt"

with open(filepath) as file_object:
    contents = file_object.read()
    print(contents)

3.1415926535 
  8979323846 
  2643383279



There are two standard functions in Python for dealing with files; open() and close(). When you open a file it will remain open until you close it. While open the file can be subjected to data loss of corruption if your code does not handle it properly. This is where with comes in. With causes python to automatically close the file once it is no longer needed. This eliminates the need to call the close() function and allows use to keep the file open for a minimum amount of time in order to prevent issues.

When designing databases for larger files the first question most programmer ask is "how many lines is the file". This is because we typically read files in on a line by line basis. We can do this in python as follows.

In [15]:
with open(filepath) as file_object:
    lines = file_object.readlines()
    
for line in lines:
    print(line)

3.1415926535 

  8979323846 

  2643383279



Let's do this with a real file.

In [16]:
filepath = "/Users/michael/Data/EQY_US_ALL_TRADE_20181105"

with open(filepath, 'r') as file_object:
    trade_data = file_object.readlines()
    
for iwho in range(3):
    print(trade_data[iwho])

Time|Exchange|Symbol|Sale Condition|Trade Volume|Trade Price|Trade Stop Stock Indicator|Trade Correction Indicator|Sequence Number|Trade Id|Source of Trade|Trade Reporting Facility|Participant Timestamp|Trade Reporting Facility TRF Timestamp|Trade Through Exempt Indicator

090004996509000|T|A| FTI|50|65.5|N|00|173001|62879130218317|C||090004995641786||1

091705411537000|D|A|  TI|12|65.93|N|00|220701|71675222906168|C|T|091705162000000|091705410778199|0



In [17]:
len(trade_data)

37419536

We have just loaded every equity trade which took place on the NYSE on November 5th 2018 into a lilst of strings. You can see the first three strings in the list above. The first one is the header which tells you what each entry means. We will go through the details of these entires as the course evolves.

The open() function can also be used to create a file,write out to a file, or append to a file. This just requires us to pass an additional argument. We have done this is the code above. In the second argument we see 'r'. This means open() is in read mode. You can pass 'w' fro write, 'a' for append, and 'r+' for read and write. If you pass nothing python assumes you are in read mode. If you call the write option and no such file exists, python will create it.

In [18]:
with open("/Users/michael/Data/A_trade.txt",'w') as file_object:
    file_object.write(trade_data[1])

In [19]:
with open("/Users/michael/Data/A_trade.txt") as file_object:
    print(file_object.read())

090004996509000|T|A| FTI|50|65.5|N|00|173001|62879130218317|C||090004995641786||1



Let's append some additional trades.

In [20]:
with open("/Users/michael/Data/A_trade.txt",'a') as file_object:
    for iwhen in range(2,10):
        file_object.write(trade_data[iwhen])

In [21]:
with open("/Users/michael/Data/A_trade.txt") as file_object:
    print(file_object.read())

090004996509000|T|A| FTI|50|65.5|N|00|173001|62879130218317|C||090004995641786||1
091705411537000|D|A|  TI|12|65.93|N|00|220701|71675222906168|C|T|091705162000000|091705410778199|0
093000012344000|N|A| O  |16450|66.03|N|00|277801|52983576808518|C||093000003816000||0
093031335250000|D|A|   I|48|66.0424|N|00|490501|71675223951689|C|T|093031327000000|093031334543995|0
093035234224000|D|A|    |100|66.13|N|00|500201|71675223956051|C|T|093035232000000|093035233601427|0
093037106236000|D|A|   I|38|65.89|N|00|502801|71675224012873|C|T|093037103000000|093037105581364|0
093037117772000|D|A|    |100|66.1|N|00|502901|71675224012874|C|T|093037111000000|093037117155788|0
093040098178000|Y|A|   I|13|65.89|N|00|528301|52983525027918|C||093040097670000||0
093046754968000|Z|A|   I|2|65.91|N|00|550801|52983525028417|C||093046754463000||0



Notice the | characters through out the file. These are refered to as pipes. NYSE uses pipes as their sperator variable or delimiter instead of commas. Each line in this file represents a trade. The pipes seperate the different peices of information about a particular trade. We would like to change this from a list of string into a list of lists so that we can access each field of a trade directly. In order to do this we will need that csv module.

In [22]:
import csv
with open("/Users/michael/Data/A_trade.txt",newline='\n') as file_object:
   trade_data_A = file_object.readlines()

buffer = []

for line in trade_data_A:
    buffer.append(line.split('|'))

trade_data_A = buffer
for line in trade_data_A:
    print(line)

['090004996509000', 'T', 'A', ' FTI', '50', '65.5', 'N', '00', '173001', '62879130218317', 'C', '', '090004995641786', '', '1\n']
['091705411537000', 'D', 'A', '  TI', '12', '65.93', 'N', '00', '220701', '71675222906168', 'C', 'T', '091705162000000', '091705410778199', '0\n']
['093000012344000', 'N', 'A', ' O  ', '16450', '66.03', 'N', '00', '277801', '52983576808518', 'C', '', '093000003816000', '', '0\n']
['093031335250000', 'D', 'A', '   I', '48', '66.0424', 'N', '00', '490501', '71675223951689', 'C', 'T', '093031327000000', '093031334543995', '0\n']
['093035234224000', 'D', 'A', '    ', '100', '66.13', 'N', '00', '500201', '71675223956051', 'C', 'T', '093035232000000', '093035233601427', '0\n']
['093037106236000', 'D', 'A', '   I', '38', '65.89', 'N', '00', '502801', '71675224012873', 'C', 'T', '093037103000000', '093037105581364', '0\n']
['093037117772000', 'D', 'A', '    ', '100', '66.1', 'N', '00', '502901', '71675224012874', 'C', 'T', '093037111000000', '093037117155788', '0\n'

## Exceptions 

Python uses object called exceptions to handle errors. Whenever an error occurs an exception is generated. If your code does not know how to handle the exception it will stop running and a trace back error will be returned. We can attempt to anticipate errors using try-except block. This allows our code to handle the anticipated error when it comes up and allows us to prevent a crash.

In [23]:
5/0

ZeroDivisionError: division by zero

In [24]:
try:
    5/0
except ZeroDivisionError:
    print("You can't divide by 0")

You can't divide by 0


Since we probably don't want to output messages like this in larger blocks of code, we could write to an error log instead.

In [25]:
try:
    5/0
except ZeroDivisionError:
    with open("/Users/michael/Documents/Stony Brook/AMS 691 Fall 2020/Lecture002/Errlog.txt",'w') as file_object:
        file_object.write("Division by zero attempted.")

In [26]:
with open("/Users/michael/Documents/Stony Brook/AMS 691 Fall 2020/Lecture002/Errlog.txt") as file_object:
    log_contents = file_object.read()
    print(log_contents)

Division by zero attempted.


## Numpy

Numerical Python or Numpy is a module which is centered around multidimensional arrays; matrices. It is written in such a way as to allow for fast implementation of these arrays. This allows it to compete with languages like C++ and Fortran when it comes to matrix operations. In quantitative finanace, and computational science more generally, Numpy is indispensable. A good partner module for Numpy is Cupy (which we will not need for this course). Cupy provides Cuda support for Numpy allowing the user to leverage GPUs to accelerate their computations. 

The basic object in Numpy is the array. Arrays can be used to represent vectors, matrices, tensors, and other objects. Here is a simple example of a vector.

In [27]:
import numpy as np
vnVector = np.array([1,2,3,4,5])
vnVector

array([1, 2, 3, 4, 5])

The behavior of arrays is very similar to lists.

In [28]:
vnVector[0]

1

In [29]:
vnVector[1:4]

array([2, 3, 4])

In [30]:
vnVector[:3]

array([1, 2, 3])

In [31]:
vnVector[2:]

array([3, 4, 5])

In [32]:
vnVector[:]

array([1, 2, 3, 4, 5])

Here we create a matrix

In [33]:
mnMatrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
mnMatrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
mnMatrix[0]

array([1, 2, 3, 4])

In [35]:
mnMatrix[1,2]

7

In [36]:
mnMatrix[1][2]

7

In [37]:
mnMatrix[0,1:4]

array([2, 3, 4])

In [38]:
mnMatrix[0,1] = 5

In [39]:
mnMatrix

array([[ 1,  5,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

There are a number of ways to get the dimension of your array, but shape is probably the one you want.

In [40]:
mnMatrix.ndim

2

In [41]:
mnMatrix.shape

(3, 4)

Like all variables in Python the complier makes assumptions about the type elements have in an array. Consider our previous example.

In [42]:
mnMatrix.dtype

dtype('int64')

We have 64-bit integer elements. If we wanted floats we should have used decimal points.

In [43]:
mnFloatMatrix = np.array([[1.2,3.6,-2.1],[0.5,2.2,1.0]])

In [44]:
mnFloatMatrix.dtype

dtype('float64')

In [45]:
vnText = np.array(['1','2','3','four'])
vnText

array(['1', '2', '3', 'four'], dtype='<U4')

In [46]:
vnText.dtype

dtype('<U4')

### Creating Arrays.

In [47]:
#Arrays can be made from lists or lists of lists
my_list = [1,2,3,4,5]
mnList = np.array(my_list)
mnList

array([1, 2, 3, 4, 5])

In [48]:
#A matrix of all zeros
mnZeros = np.zeros((3,4))
mnZeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
#A matrix of all ones
mnOnes = np.ones((4,3))
mnOnes

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
#More generally full can be used to make an arbitrary size matrix with identical entires
mnFives = np.full((3,4),5)
mnFives

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [51]:
#Create a random matrix
mnRand = np.empty((2,2))
mnRand

array([[2.00000000e+000, 3.11107978e+231],
       [9.88131292e-324, 2.82465084e-309]])

In [52]:
#Similar to using range is arange in np
vnVec = np.arange(6)
vnVec

array([0, 1, 2, 3, 4, 5])

In [53]:
#Reshape allows us to dictate the dimensions of the matrix
vnVec.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [54]:
#We can create mnMatrix from above using arange and reshape
mnMatrix = np.arange(1,13).reshape(3,4)
mnMatrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
mnMatrix.dtype

dtype('int64')

In [56]:
#Can specify data type or step size
vnVec1 = np.arange(0,5, dtype=float)
vnVec1.dtype

dtype('float64')

In [57]:
vnVec2 = np.arange(2,5,0.5)
vnVec2

array([2. , 2.5, 3. , 3.5, 4. , 4.5])

In [58]:
#Identity matrix
mnIden = np.identity(3)
mnIden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
#The eye method is similar, but it controls for size
mnDiag = np.eye(3,4)
mnDiag

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### Array Operations

You and apply standard arithmetic operators to vectors and matrices in Python, but be aware that they operate pointwise. In order to do matrix multiplication and inverse we must use special Numpy methods.

In [60]:
A = np.arange(16).reshape((4,4))
B = np.arange(1,17).reshape((4,4))
print(A)
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [61]:
print(A + B)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]]


In [62]:
print(A - B)

[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [63]:
print(A * B)

[[  0   2   6  12]
 [ 20  30  42  56]
 [ 72  90 110 132]
 [156 182 210 240]]


In [64]:
print(A / B)

[[0.         0.5        0.66666667 0.75      ]
 [0.8        0.83333333 0.85714286 0.875     ]
 [0.88888889 0.9        0.90909091 0.91666667]
 [0.92307692 0.92857143 0.93333333 0.9375    ]]


In [65]:
print(A % B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [66]:
print(3*A)

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]
 [36 39 42 45]]


There are also numpy methods like add(), subtract(), multiply(), and divide() which do element wise operations too. There are some methods which do not have symbolic equivalents.

In [67]:
print(np.add(A,B))

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]]


In [68]:
#sqrt() takes square roots element wise
print(np.sqrt(A))

[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]
 [3.46410162 3.60555128 3.74165739 3.87298335]]


In [69]:
#sum() adds up all the elements in the array
print(np.sum(A))

120


Matrix multiplication is performed using the dot() method. This can also be used on vectors to compute the dot product. Alternativly you can also use matmul().

In [70]:
print(np.dot(A,B))

[[ 62  68  74  80]
 [174 196 218 240]
 [286 324 362 400]
 [398 452 506 560]]


In [71]:
print(np.dot(B,A))

[[ 80  90 100 110]
 [176 202 228 254]
 [272 314 356 398]
 [368 426 484 542]]


In [72]:
#You can also use matmul
print(np.matmul(A,B))

[[ 62  68  74  80]
 [174 196 218 240]
 [286 324 362 400]
 [398 452 506 560]]


In [73]:
print(np.matmul(B,A))

[[ 80  90 100 110]
 [176 202 228 254]
 [272 314 356 398]
 [368 426 484 542]]


In [74]:
#The dot product of the first row of A with the first column of B
print(np.dot(A[0],B[:,0]))

62


We can do the outer product of two vectors. Recall that given an $n \times 1$ vector $u$ and a $n \times 1$ vector $v$ we define the outer product $u \otimes v$ as the $m \times n$ matrix
$$u \otimes v = \begin{pmatrix}
u_1v_1 & \cdots & u_1v_n\\
\vdots & \ddots & \vdots \\
u_mv_1 & \cdots &u_mv_n
\end{pmatrix}$$

In [75]:
#outer() produces the outer product of two vectors.
print(np.outer(A[0],B[:,0]))

[[ 0  0  0  0]
 [ 1  5  9 13]
 [ 2 10 18 26]
 [ 3 15 27 39]]


A generalization of the outer product to matrices is the Kronecker product. We can do the Kronecker product as well. Recall that given an $n \times m$ matrix $A$ and a $p \times q$ matrix $B$ we define the Kronecker product $A \otimes B$ as the $pm \times qn$ matrix
$$A \otimes B = \begin{pmatrix}
a_{11}B & \cdots & a_{1n}B\\
\vdots & \ddots & \vdots \\
a_{m1}B & \cdots &a_{mn}B
\end{pmatrix}$$

In [76]:
#Kronecker product
print(np.kron(A,B))

[[  0   0   0   0   1   2   3   4   2   4   6   8   3   6   9  12]
 [  0   0   0   0   5   6   7   8  10  12  14  16  15  18  21  24]
 [  0   0   0   0   9  10  11  12  18  20  22  24  27  30  33  36]
 [  0   0   0   0  13  14  15  16  26  28  30  32  39  42  45  48]
 [  4   8  12  16   5  10  15  20   6  12  18  24   7  14  21  28]
 [ 20  24  28  32  25  30  35  40  30  36  42  48  35  42  49  56]
 [ 36  40  44  48  45  50  55  60  54  60  66  72  63  70  77  84]
 [ 52  56  60  64  65  70  75  80  78  84  90  96  91  98 105 112]
 [  8  16  24  32   9  18  27  36  10  20  30  40  11  22  33  44]
 [ 40  48  56  64  45  54  63  72  50  60  70  80  55  66  77  88]
 [ 72  80  88  96  81  90  99 108  90 100 110 120  99 110 121 132]
 [104 112 120 128 117 126 135 144 130 140 150 160 143 154 165 176]
 [ 12  24  36  48  13  26  39  52  14  28  42  56  15  30  45  60]
 [ 60  72  84  96  65  78  91 104  70  84  98 112  75  90 105 120]
 [108 120 132 144 117 130 143 156 126 140 154 168 135 150 165 

There are two ways to implement the transpose.

In [77]:
print(A.T)

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [78]:
print(A.transpose())

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [79]:
#Trace of a matrix
A.trace()

30

## Scipy

The SciPy library is one of the core packages that make up the SciPy stack. It provides many user-friendly and efficient numerical routines, such as routines for numerical integration, interpolation, optimization, linear algebra, and statistics.

### The linalg Submodule

Most of the other matrix operations and manipulations numpy has are contained in the linalg submodule. Unfortunately this submodule is very light in numpy. Scipy also contains a linalg submodlue. In scipy the submodule can do everything the one in numpy can and much much more. Even some of the linalg functions that numpy and scipy have in common are more limited on the scipy side. In the end you are better off creating arrays in numpy and working with them in scipy most of the time. 

In [80]:
from scipy import linalg

In [81]:
mnGoodMatrix = np.dot(B,B.T) + np.identity(4)

We can solve linear equations of the form $$Ax = b$$ for $x$.

In [82]:
linalg.solve(np.array([[1,2],[3,4]]),np.array([5,6]))

array([-4. ,  4.5])

In [83]:
#Find the Euclidean norm of a matrix or vector
print(linalg.norm(mnGoodMatrix))

1492.719665576896


In [85]:
#Compute the determinant of a matrix
print(linalg.det(mnGoodMatrix))

7897.000000000006


In [86]:
#Find the inverse of a matrix
print(linalg.inv(mnGoodMatrix))

[[ 0.42889705 -0.33303786 -0.09497277  0.14309231]
 [-0.33303786  0.73483601 -0.19729011 -0.12941623]
 [-0.09497277 -0.19729011  0.70039255 -0.40192478]
 [ 0.14309231 -0.12941623 -0.40192478  0.32556667]]


We can also compute the Moore-Penrose inverse for matrices which are not invertable. Remember this is defined as $$A^+ = (A^*A)^{-1}A$$ when $A$ has linearly independant columns. When it does not this is more generally defined satsifying four conditions.

In [87]:
#Notice A is not invertable
print(linalg.det(A))

0.0


In [88]:
#pinv() gives the Moore-Penrose inverse
print(linalg.pinv(A))

[[-2.62500000e-01 -1.37500000e-01 -1.25000000e-02  1.12500000e-01]
 [-1.00000000e-01 -5.00000000e-02  1.53250756e-17  5.00000000e-02]
 [ 6.25000000e-02  3.75000000e-02  1.25000000e-02 -1.25000000e-02]
 [ 2.25000000e-01  1.25000000e-01  2.50000000e-02 -7.50000000e-02]]


In [89]:
#Find the Euclidean norm of a matrix or vector
print(linalg.norm(mnGoodMatrix))

1492.719665576896


In [90]:
#Here eig() returns 2 arrays. The first is eigenvalues and the second the corresponding eigenvectors
print(linalg.eig(mnGoodMatrix))

(array([1.49270962e+03+0.j, 5.29037925e+00+0.j, 1.00000000e+00+0.j,
       1.00000000e+00+0.j]), array([[-0.13472212,  0.82574206,  0.47727482, -0.24409588],
       [-0.3407577 ,  0.4288172 , -0.83665614, -0.04000443],
       [-0.54679327,  0.03189234,  0.24148784,  0.81229651],
       [-0.75282884, -0.36503251,  0.11789349, -0.5281962 ]]))


Recall that the condition number of a matrix gives us a way to measure the numerical stability or instability it contributes to computations it is involved in. Condition number is dependant ona choice of norm. A standard choice is the Frobenious norm which is the square root of the sum of the squares of the matirx entries. Under this norm the condition number has the simple form. $$\kappa(A) = \frac{\sigma_{max}(A)}{\sigma_{min}(A)}$$ where $\sigma_{max}(A)$ and $\sigma_{min}(A)$ are the largest and smallest singular values of $A$.

In [91]:
#We can compute the condition number relative to the Frobenious norm
print(linalg.expm_cond(A))

37.451119230344645


### Matrix Functions

The linalg submodule in scipy also has a large number of matrix functions we can apply. This is again something that is not widely avalible in numpy.

We can compute matrix powers using fractional_matrix_power(). This method is present in numpy too, however you can only raise matrices to integer powers in numpy.

In [92]:
print(linalg.fractional_matrix_power(mnGoodMatrix,3))

[[6.03676910e+07 1.52690050e+08 2.45012410e+08 3.37334770e+08]
 [1.52690050e+08 3.86204539e+08 6.19719026e+08 8.53233514e+08]
 [2.45012410e+08 6.19719026e+08 9.94425643e+08 1.36913226e+09]
 [3.37334770e+08 8.53233514e+08 1.36913226e+09 1.88503100e+09]]


In [93]:
print(linalg.fractional_matrix_power(mnGoodMatrix,0.5))

[[ 2.5695492   2.18810942  2.80666964  3.42522986]
 [ 2.18810942  5.60915274  7.03019607  9.45123939]
 [ 2.80666964  7.03019607 12.25372249 15.47724891]
 [ 3.42522986  9.45123939 15.47724891 22.50325844]]


In [94]:
#The matrix exponential
print(linalg.expm(mnIden))

[[2.71828183 0.         0.        ]
 [0.         2.71828183 0.        ]
 [0.         0.         2.71828183]]


In [95]:
#The matrix log
print(linalg.logm(mnGoodMatrix))

[[1.26853386 0.9253877  0.58224154 0.23909537]
 [0.9253877  1.15494559 1.38450348 1.61406137]
 [0.58224154 1.38450348 2.18676542 2.98902736]
 [0.23909537 1.61406137 2.98902736 4.36399335]]


In [96]:
#There are all the standard matrix trig and hyperbolic trig functions in scipy, here is sine
print(linalg.sinm(mnGoodMatrix))

[[-0.32659599 -0.65325955 -0.13845213  0.37635528]
 [-0.65325955  0.38418388 -0.26131465 -0.0653422 ]
 [-0.13845213 -0.26131465  0.45729382 -0.50703968]
 [ 0.37635528 -0.0653422  -0.50703968 -0.10726618]]


### Matrix Decompositions

The scipy linalg submodule contains a large number of matrix decompsitions. A small subset of these decompostions are contained in numpy, but there is nothing unique to numpy.

An LU decompositon of $A$ is a factorization of the matrix into a lower and upper triangular matrices $L$ and $U$. $$A = LU$$

In [97]:
#LU decomposition 
print(linalg.lu(mnGoodMatrix))

(array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]]), array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.20666667,  1.        ,  0.        ,  0.        ],
       [ 0.46666667,  0.36512668,  1.        ,  0.        ],
       [ 0.73333333,  0.23845007, -0.32199118,  1.        ]]), array([[150.        , 382.        , 614.        , 847.        ],
       [  0.        ,  -8.94666667, -16.89333333, -25.04666667],
       [  0.        ,   0.        ,  -2.36512668,  -4.12146051],
       [  0.        ,   0.        ,   0.        ,  -2.48802773]]))


The singular value decomposition or SVD of a $m \times n$ matrix A is a factorization of $A$ in the form
$$A = U \Sigma V^*$$
where U is an $m \times m$ unitary matrix, $\Sigma$ is an $m \times n$ rectangular diagonal matrix, and $V$ is a $n \times n$ unitary matrix. In the case that $A$ is real the matrices $U$ and $V$ are orthogonal. The elements onthe diagonal of $\Sigma$ are referred to as the singular values.

In [98]:
#The SVD
print(linalg.svd(mnGoodMatrix))

(array([[-0.13472212, -0.82574206,  0.26062519, -0.48174112],
       [-0.3407577 , -0.4288172 ,  0.01156838,  0.83658005],
       [-0.54679327, -0.03189234, -0.80501233, -0.22793672],
       [-0.75282884,  0.36503251,  0.53281876, -0.1269022 ]]), array([1.49270962e+03, 5.29037925e+00, 1.00000000e+00, 1.00000000e+00]), array([[-0.13472212, -0.3407577 , -0.54679327, -0.75282884],
       [-0.82574206, -0.4288172 , -0.03189234,  0.36503251],
       [ 0.26062519,  0.01156838, -0.80501233,  0.53281876],
       [-0.48174112,  0.83658005, -0.22793672, -0.1269022 ]]))


In [99]:
#We can just return the singular values if we like
print(linalg.svdvals(mnGoodMatrix))

[1.49270962e+03 5.29037925e+00 1.00000000e+00 1.00000000e+00]


Recall that the range of a matrix $A$ is the space generated by the span of the columns of $A$ were as the null space is the space of all solutions to the equations $$Ax = 0$$. These spaces are fundamental and thus having a basis for them is always handy.

In [100]:
#An orthonormal basis for the range
print(linalg.orth(mnGoodMatrix))

[[-0.13472212 -0.82574206  0.26062519 -0.48174112]
 [-0.3407577  -0.4288172   0.01156838  0.83658005]
 [-0.54679327 -0.03189234 -0.80501233 -0.22793672]
 [-0.75282884  0.36503251  0.53281876 -0.1269022 ]]


In [101]:
#An orthonormal basis for the null space
print(linalg.null_space(A))

[[ 0.5427818   0.0734024 ]
 [-0.66899815 -0.50243554]
 [-0.29034911  0.78466387]
 [ 0.41656546 -0.35563073]]


Given a positive definite matrix $A$ the Cholesky decomposition is a factorization of the matrix into a lower triangular matrix and it's conjugate transpose. $$A = LL^*$$
This factorization is unique and is sometimes referred to as a way to take a square root of a matrix.

In [102]:
#The Cholesky decomposition
#An orthonormal basis for the range
print(linalg.cholesky(mnGoodMatrix))

[[ 5.56776436 12.57237114 19.75658322 26.9407953 ]
 [ 0.          4.11527446  7.19585134 10.51942538]
 [ 0.          0.          2.21294891  2.73197193]
 [ 0.          0.          0.          1.75258879]]


The polar decomposition is a factorization of any square matrix $A$ which give the form
$$A = UP$$
where $U$ is unitray and $P$ is is a semi-positive definite Hermitian matrix. Thus $A$ is relized as a rotation and a scaling.

In [103]:
#The polar decomposition
print(linalg.polar(mnGoodMatrix))

(array([[ 1.00000000e+00,  2.02268757e-14, -2.38420395e-14,
         8.54871729e-15],
       [-1.96370697e-14,  1.00000000e+00,  1.67921232e-14,
        -8.27116153e-15],
       [ 2.39253062e-14, -1.64313008e-14,  1.00000000e+00,
         3.42087469e-15],
       [-8.46545056e-15,  8.54871729e-15, -3.24393290e-15,
         1.00000000e+00]]), array([[ 31.,  70., 110., 150.],
       [ 70., 175., 278., 382.],
       [110., 278., 447., 614.],
       [150., 382., 614., 847.]]))


The QR decomposition is a factorization of any matrix $A$ which gives the form
$$A = QR$$
where $Q$ is orthogonal and $R$ is upper triangular.

In [104]:
#The QR decomposition
print(linalg.qr(mnGoodMatrix))

(array([[-0.15411446,  0.926988  , -0.22306249,  0.2592009 ],
       [-0.34800039,  0.2196275 ,  0.88074011, -0.23442771],
       [-0.54685776,  0.01323917, -0.41316499, -0.72805632],
       [-0.74571513, -0.30377908, -0.06192481,  0.58973938]]), array([[ -201.14919836,  -508.57771662,  -816.01120631, -1123.444696  ],
       [    0.        ,    -9.03914606,   -17.57731995,   -26.22612375],
       [    0.        ,     0.        ,    -2.39770769,    -3.1502701 ],
       [    0.        ,     0.        ,     0.        ,     1.81142431]]))


The Schur decomposition of any matrix $A$ is written
$$A = QUQ^{-1}$$
where $Q$ is unitary and $U$ is upper triangular. Thus $A$ can be expressed by a unitarily equivalent matrix.

In [105]:
#The Schur decomposition
print(linalg.schur(mnGoodMatrix))

(array([[ 1.49270962e+03, -1.90680804e-14, -1.00684644e-14,
        -1.68894760e-13],
       [ 0.00000000e+00,  5.29037925e+00,  3.19487163e-14,
        -2.76313947e-15],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         1.91094572e-15],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]]), array([[-0.13472212,  0.82574206,  0.47727482, -0.26871686],
       [-0.3407577 ,  0.4288172 , -0.83665614,  0.0025495 ],
       [-0.54679327,  0.03189234,  0.24148784,  0.80105157],
       [-0.75282884, -0.36503251,  0.11789349, -0.53488422]]))


A Hessenberg matrix is a square matrix which is almost triangular. It has one subdiagonal which is non-zero.

In [106]:
#The Hessenberg form
print(linalg.hessenberg(mnGoodMatrix))

[[ 3.10000000e+01 -1.98746069e+02 -3.43995474e-14 -3.24941613e-14]
 [-1.98746069e+02  1.46554177e+03  1.46845360e+01  1.49142147e-13]
 [ 0.00000000e+00  1.46845360e+01  2.45822785e+00 -2.40918396e-14]
 [ 0.00000000e+00  0.00000000e+00 -1.98203978e-14  1.00000000e+00]]


### Special Matrices

Scipy has the ability to generate a number of standard matrix structures which are used in many areas in science. We will mentions a number of these structures which play a role in various parts of quantitative finance.

In [107]:
print(linalg.circulant([1,4,7]))

[[1 7 4]
 [4 1 7]
 [7 4 1]]


In [108]:
print(linalg.companion([1,4,7,-11,2]))

[[-4. -7. 11. -2.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]


In [109]:
print(linalg.hadamard(4))

[[ 1  1  1  1]
 [ 1 -1  1 -1]
 [ 1  1 -1 -1]
 [ 1 -1 -1  1]]


In [110]:
print(linalg.hankel([1,4,7,-11,2]))

[[  1   4   7 -11   2]
 [  4   7 -11   2   0]
 [  7 -11   2   0   0]
 [-11   2   0   0   0]
 [  2   0   0   0   0]]


In [111]:
print(linalg.hankel([1,4,7,-11,2],[2,8,6,3,9,1]))

[[  1   4   7 -11   2   8]
 [  4   7 -11   2   8   6]
 [  7 -11   2   8   6   3]
 [-11   2   8   6   3   9]
 [  2   8   6   3   9   1]]


In [112]:
print(linalg.toeplitz([1,4,7,-11,2]))

[[  1   4   7 -11   2]
 [  4   1   4   7 -11]
 [  7   4   1   4   7]
 [-11   7   4   1   4]
 [  2 -11   7   4   1]]


## Pandas

The Pandas module is specially crafted for data manipulation and analysis. It provides tools and structures which allow for the fast and easy manipulation of tabular and time series data. This module pairs well with the tools and structures in numpy and scipy. In addition matplotlib can be leveraged on top of all of these modules to provide good visual tools for presentation and analysis. An interesting historical side note is that Pandas was developed by quants out of the need for better performance.

The primary structures in Pandas are series and data frame. A series is a one-dimensional array like structure whos values are index by some kind of label.A DataFrame represents a rectangular table of data and contains an ordered collection of columns, each of which can be a different value type. Pandas can handle a wide array of data formats including csv, json, SQL, and Excel. 

In [113]:
import pandas as pd

In [116]:
my_list = [1.34,1.25,1.97,2.08]

In [117]:
my_list

[1.34, 1.25, 1.97, 2.08]

In [119]:
my_list[2]

1.97

In [114]:
price_series = pd.Series([1.34,1.25,1.97,2.08])
price_series

0    1.34
1    1.25
2    1.97
3    2.08
dtype: float64

In [115]:
price_series[2]

1.97

Here we have a time series of prices. The series structure (notice the capitalization when you call it) shows that our price are currently indexed by integers. This make the current structure very similar to a list. We can change the indices by passing and index option when we create the series.

In [120]:
price_series = pd.Series([1.34,1.25,1.97,2.08], index=["2020/9/1", "2020/9/2", "2020/9/3","2020/9/4"])
price_series

2020/9/1    1.34
2020/9/2    1.25
2020/9/3    1.97
2020/9/4    2.08
dtype: float64

In [121]:
price_series["2020/9/3"]

1.97

Another way to do this is to pass series a dictionary.

In [122]:
price_series = pd.Series({"2020/9/1":1.34,"2020/9/2":1.25,"2020/9/3":1.97,"2020/9/4":2.08})
price_series

2020/9/1    1.34
2020/9/2    1.25
2020/9/3    1.97
2020/9/4    2.08
dtype: float64

One important aspect of series is that they will handle missing values. In order to take advantage of this series must be passed a dictionary.

In [123]:
price_series = pd.Series({"2020/9/1":1.34,"2020/9/2":1.25,"2020/9/3":1.97,"2020/9/4":2.08}, index=["2020/9/1", "2020/9/2", "2020/9/3","2020/9/4","2020/9/5"])
price_series

2020/9/1    1.34
2020/9/2    1.25
2020/9/3    1.97
2020/9/4    2.08
2020/9/5     NaN
dtype: float64

Now we add the price.

In [124]:
price_series["2020/9/5"] = 2.01
price_series

2020/9/1    1.34
2020/9/2    1.25
2020/9/3    1.97
2020/9/4    2.08
2020/9/5    2.01
dtype: float64

Numpy and scipy functions and methods can be used on series object. When this is done only the values of the series will change, not the values of the indices.

In [125]:
np.log(1 + price_series)

2020/9/1    0.850151
2020/9/2    0.810930
2020/9/3    1.088562
2020/9/4    1.124930
2020/9/5    1.101940
dtype: float64

One important thing you must always consider when working with financial data is maintaining alignment. The series() object will use index values to maintain the alignment of two series when doing operations on them.

In [126]:
return_series = pd.Series({"2020/9/1":-.134,"2020/9/2":0.25,"2020/9/3":0.097,"2020/9/4":0.08,"2020/9/5":-0.48})
risk_free_series = pd.Series({"2020/9/1":0.004,"2020/9/2":0.003,"2020/9/3":0.002,"2020/9/4":0.002,"2020/9/5":0.001})
adjlogreturn_series = np.log(1 + return_series - risk_free_series)
adjlogreturn_series

2020/9/1   -0.148500
2020/9/2    0.220741
2020/9/3    0.090754
2020/9/4    0.075107
2020/9/5   -0.655851
dtype: float64

The data frame object has a tabular format. It's structure is amenable to a wider array of applications and data types. We can use a data frame to store a collection of time series. Just like a series if we choose not to include an index data frame will use 0, 1, 2, 3, ... by default.

In [127]:
dbReturns = pd.DataFrame({"AAPL":[0.36,0.05,-0.26],"IBM":[0.04,0.03,-0.02],"MSFT":[0.12,0.01,-0.34]}
                         ,index=["2020/9/1", "2020/9/2", "2020/9/3"])
dbReturns

AAPL   IBM  MSFT
2020/9/1  0.36  0.04  0.12
2020/9/2  0.05  0.03  0.01
2020/9/3 -0.26 -0.02 -0.34

You should think of the columns of a data frame as a series.

In [128]:
dbReturns["AAPL"]

2020/9/1    0.36
2020/9/2    0.05
2020/9/3   -0.26
Name: AAPL, dtype: float64

In [129]:
dbReturns.AAPL

2020/9/1    0.36
2020/9/2    0.05
2020/9/3   -0.26
Name: AAPL, dtype: float64

The same goes for rows, but you need to access then with the loc() method.

In [130]:
dbReturns.loc["2020/9/1"]

AAPL    0.36
IBM     0.04
MSFT    0.12
Name: 2020/9/1, dtype: float64

We can extract the data in a data frame as a array so that we can use the tools in the numpy module.

In [131]:
dbReturns.values

array([[ 0.36,  0.04,  0.12],
       [ 0.05,  0.03,  0.01],
       [-0.26, -0.02, -0.34]])

As we mentioned earlier pandas can handle a large collection of data types. All of them can be loaded into data frames. There are methods for each type of data you wish to load into a data frame. read_csv() handles csv files, read_json json file, and read_excel excel files. There are many many more type. See I/O API documentation for all the types avalible and their corosponding methods.

In [132]:
index_return_series = pd.read_csv("/Users/michael/Desktop/FQS_Priority/Invested_Funds/RIEF/IndexReturns.csv")

In [133]:
index_return_series

Unnamed: 0      GSPC       RUT      N225   ETZD.PA
0     2017-01-01  0.000000  0.000000  0.000000  0.000000
1     2017-01-02  0.000000  0.000000  0.000000  0.000000
2     2017-01-03  0.000000  0.000000  0.000000  0.003145
3     2017-01-04  0.005722  0.016448  0.000000 -0.000884
4     2017-01-05 -0.000771 -0.011535 -0.003750  0.001771
...          ...       ...       ...       ...       ...
1265  2020-06-19 -0.005649 -0.006095  0.005517  0.005777
1266  2020-06-20  0.000000  0.000000  0.000000  0.000000
1267  2020-06-21  0.000000  0.000000  0.000000  0.000000
1268  2020-06-22  0.000000  0.000000 -0.001847  0.000000
1269  2020-06-23  0.000000  0.000000  0.000000  0.000000

[1270 rows x 5 columns]

In [134]:
index_return_series.values

array([['2017-01-01', 0.0, 0.0, 0.0, 0.0],
       ['2017-01-02', 0.0, 0.0, 0.0, 0.0],
       ['2017-01-03', 0.0, 0.0, 0.0, 0.003144977],
       ...,
       ['2020-06-21', 0.0, 0.0, 0.0, 0.0],
       ['2020-06-22', 0.0, 0.0, -0.0018470539999999999, 0.0],
       ['2020-06-23', 0.0, 0.0, 0.0, 0.0]], dtype=object)

When you have a large data frame like this the head method is useful to get an idea of what you are working with.

In [135]:
index_return_series.head()

Unnamed: 0      GSPC       RUT     N225   ETZD.PA
0  2017-01-01  0.000000  0.000000  0.00000  0.000000
1  2017-01-02  0.000000  0.000000  0.00000  0.000000
2  2017-01-03  0.000000  0.000000  0.00000  0.003145
3  2017-01-04  0.005722  0.016448  0.00000 -0.000884
4  2017-01-05 -0.000771 -0.011535 -0.00375  0.001771

We are going to have to reindex this. Since the index for the data frame is an attribute we can access it.

In [136]:
index_return_series.index

RangeIndex(start=0, stop=1270, step=1)

In [137]:
index_return_series["Unnamed: 0"]

0       2017-01-01
1       2017-01-02
2       2017-01-03
3       2017-01-04
4       2017-01-05
           ...    
1265    2020-06-19
1266    2020-06-20
1267    2020-06-21
1268    2020-06-22
1269    2020-06-23
Name: Unnamed: 0, Length: 1270, dtype: object

In [138]:
index = list(index_return_series["Unnamed: 0"])

In [139]:
index

['2017-01-01',
 '2017-01-02',
 '2017-01-03',
 '2017-01-04',
 '2017-01-05',
 '2017-01-06',
 '2017-01-07',
 '2017-01-08',
 '2017-01-09',
 '2017-01-10',
 '2017-01-11',
 '2017-01-12',
 '2017-01-13',
 '2017-01-14',
 '2017-01-15',
 '2017-01-16',
 '2017-01-17',
 '2017-01-18',
 '2017-01-19',
 '2017-01-20',
 '2017-01-21',
 '2017-01-22',
 '2017-01-23',
 '2017-01-24',
 '2017-01-25',
 '2017-01-26',
 '2017-01-27',
 '2017-01-28',
 '2017-01-29',
 '2017-01-30',
 '2017-01-31',
 '2017-02-01',
 '2017-02-02',
 '2017-02-03',
 '2017-02-04',
 '2017-02-05',
 '2017-02-06',
 '2017-02-07',
 '2017-02-08',
 '2017-02-09',
 '2017-02-10',
 '2017-02-11',
 '2017-02-12',
 '2017-02-13',
 '2017-02-14',
 '2017-02-15',
 '2017-02-16',
 '2017-02-17',
 '2017-02-18',
 '2017-02-19',
 '2017-02-20',
 '2017-02-21',
 '2017-02-22',
 '2017-02-23',
 '2017-02-24',
 '2017-02-25',
 '2017-02-26',
 '2017-02-27',
 '2017-02-28',
 '2017-03-01',
 '2017-03-02',
 '2017-03-03',
 '2017-03-04',
 '2017-03-05',
 '2017-03-06',
 '2017-03-07',
 '2017-03-

In [140]:
index_return_series.index = index

In [141]:
index_return_series

Unnamed: 0      GSPC       RUT      N225   ETZD.PA
2017-01-01  2017-01-01  0.000000  0.000000  0.000000  0.000000
2017-01-02  2017-01-02  0.000000  0.000000  0.000000  0.000000
2017-01-03  2017-01-03  0.000000  0.000000  0.000000  0.003145
2017-01-04  2017-01-04  0.005722  0.016448  0.000000 -0.000884
2017-01-05  2017-01-05 -0.000771 -0.011535 -0.003750  0.001771
...                ...       ...       ...       ...       ...
2020-06-19  2020-06-19 -0.005649 -0.006095  0.005517  0.005777
2020-06-20  2020-06-20  0.000000  0.000000  0.000000  0.000000
2020-06-21  2020-06-21  0.000000  0.000000  0.000000  0.000000
2020-06-22  2020-06-22  0.000000  0.000000 -0.001847  0.000000
2020-06-23  2020-06-23  0.000000  0.000000  0.000000  0.000000

[1270 rows x 5 columns]

In [142]:
del index_return_series["Unnamed: 0"]

In [143]:
index_return_series

GSPC       RUT      N225   ETZD.PA
2017-01-01  0.000000  0.000000  0.000000  0.000000
2017-01-02  0.000000  0.000000  0.000000  0.000000
2017-01-03  0.000000  0.000000  0.000000  0.003145
2017-01-04  0.005722  0.016448  0.000000 -0.000884
2017-01-05 -0.000771 -0.011535 -0.003750  0.001771
...              ...       ...       ...       ...
2020-06-19 -0.005649 -0.006095  0.005517  0.005777
2020-06-20  0.000000  0.000000  0.000000  0.000000
2020-06-21  0.000000  0.000000  0.000000  0.000000
2020-06-22  0.000000  0.000000 -0.001847  0.000000
2020-06-23  0.000000  0.000000  0.000000  0.000000

[1270 rows x 4 columns]

In [145]:
mnIndexReturns = index_return_series.values

In [150]:
mnIndexReturns[:4]

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.00314498],
       [ 0.00572227,  0.01644828,  0.        , -0.0008845 ]])

In [149]:
print(linalg.expm_cond(mnIndexReturns[:4]))

0.00893596539226695
